# This file was generated by GoReleaser. DO NOT EDIT.
cask "dataagent" do
  version "0.1.0-rc.1"

  on_macos do
    on_intel do
      sha256 "7f80f72e537dd13fa473aebf3b17657db33cb4b76a9fb9e5f8d73eded1900dad"
      url "https://github.com/data-agent-co/homebrew-tap/releases/download/v#{version}/dataagent_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6f5ffda00ecc81f645d0e9fc4847c7b313cc7283686bae27225d852b035cbd24"
      url "https://github.com/data-agent-co/homebrew-tap/releases/download/v#{version}/dataagent_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "30d6f135ccf1732a53794fe3ca75551cfffaa149972d6c7ea03bf31644e4d978"
      url "https://github.com/data-agent-co/homebrew-tap/releases/download/v#{version}/dataagent_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fa8b5a7d2c44fe17a7abb5d9158d4a609ed7e701ad603a876e4705e35b4a9eff"
      url "https://github.com/data-agent-co/homebrew-tap/releases/download/v#{version}/dataagent_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dataagent"
  desc "DataAgent CLI — work with DataAgent from your terminal"
  homepage "https://data-agent.co"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dataagent"
  bash_completion "completions/dataagent.bash"
  fish_completion "completions/dataagent.fish"
  zsh_completion "completions/dataagent.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dataagent"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Shell completions (bash, zsh, fish) were installed.
    Open a new terminal to start using them.
    If zsh completions don't appear, initialize Homebrew's completions:
    https://docs.brew.sh/Shell-Completion
  EOS
end
