# This file was generated by GoReleaser. DO NOT EDIT.
cask "dataagent" do
  version "0.2.0-rc.1"

  on_macos do
    on_intel do
      sha256 "15de163b1580600a4cf902ef0080c82e942d4ba80deae0bd99a7a36e212de15d"
      url "https://github.com/data-agent-co/homebrew-tap/releases/download/v#{version}/dataagent_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7324aa3fe9b542bf55b128e4d1a6b8c48eca177b88f9d5aa7648100ac7843bf3"
      url "https://github.com/data-agent-co/homebrew-tap/releases/download/v#{version}/dataagent_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "134822a6b43267f1e5f5f8904a4673804d7d52adcaa37c8a946794ea56d20690"
      url "https://github.com/data-agent-co/homebrew-tap/releases/download/v#{version}/dataagent_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d6b09e11768a4617e0d7fb3df7fa1a68b5e326deeeea97654c32a0fe519a78fa"
      url "https://github.com/data-agent-co/homebrew-tap/releases/download/v#{version}/dataagent_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dataagent"
  desc "DataAgent CLI — work with DataAgent from your terminal"
  homepage "https://data-agent.co"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dataagent"
  bash_completion "completions/dataagent.bash"
  fish_completion "completions/dataagent.fish"
  zsh_completion "completions/dataagent.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dataagent"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Shell completions (bash, zsh, fish) were installed.
    Open a new terminal to start using them.
    If zsh completions don't appear, initialize Homebrew's completions:
    https://docs.brew.sh/Shell-Completion
  EOS
end
