# This file was generated by GoReleaser. DO NOT EDIT.
cask "dataagent" do
  version "0.1.0-rc.1"

  on_macos do
    on_intel do
      sha256 "46a5916c772defbc149e015689b419ff7f107950ce0f7d9938b438ac86f5d2be"
      url "https://github.com/data-agent-co/homebrew-tap/releases/download/v#{version}/dataagent_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5917765928e788f26db6dd1f562ce641dea2e62b2c883475d62a379c93b25fe1"
      url "https://github.com/data-agent-co/homebrew-tap/releases/download/v#{version}/dataagent_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c54e89dbbe2da9bf44e4ed0e5080410337be56464b93655c9685a6ce4002b536"
      url "https://github.com/data-agent-co/homebrew-tap/releases/download/v#{version}/dataagent_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d967d46a37b572771e201efcf548452a250cc02f6a62c347f92a9922af662361"
      url "https://github.com/data-agent-co/homebrew-tap/releases/download/v#{version}/dataagent_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dataagent"
  desc "DataAgent CLI — work with DataAgent from your terminal"
  homepage "https://data-agent.co"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dataagent"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dataagent"]
    end
  end
  generate_completions_from_executable "dataagent", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
